import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google"; // Google Fonts에서 대체 폰트 가져오기
import "./globals.css";

// Inter 폰트 설정
const interSans = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});

// Roboto Mono 폰트 설정
const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${interSans.variable} ${robotoMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
